server:
  port: 8761

spring:
  application:
    name: EurekaServer

eureka:
  server:
    response-cache-update-interval-ms: 5000 # 캐싱 업데이트 주기(5초마다 업데이트)
  client:
    register-with-eureka: false # 서비스에 자신을 등록하지 않음
    fetch-registry: false # 레지스트리 정보를 로컬에 캐싱하지 않음
