server:
  port: 8888

spring:
  application:
    name: ConfigServer
  profiles:
    active: native, default
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    refresh:
      enabled: true
